### ISSUE TITLE
Possibility of import to Calckey

### ISSUE THREAD

**Issue by Ciechom** [MastodonContentMover/repo#1]
Hey, I used a utility to post to mastodon to actually post to calckey, so I thought I'll try to use this one too :) but unfortunately before authentication it checks for mastodon version number which throws an expected error, since it's not in fact mastodon instance I wanted to post to but calckey. I thought about commenting out the version check to test if it works, but I can't seem to find it in the source code. Can you help me find it, so I can test it properly?

**Comment by MastodonContentMover** [comment]
Sorry, the purpose of this tool is to move posts between Mastodon instances. It has nothing to do with Calckey, which has a different API. If you want to move data into Calckey, you will need to use a tool that is intended to do that.

**Comment by MastodonContentMover** [comment]
(Closing as not planned)
